[package]
name = "contre-frappe"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_dev_tools = "0.14.2"
bevy_fps_controller = "0.3.0"
bevy_rapier3d = "0.27.0"
serde = { version = "1.0.214", features = ["derive"] }
